name: Push_Docker Main

on:
  schedule:
    - cron:  '39 8 * * 5'
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Push_Docker DEV
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: yanik39/equivs:latest
      -
        name: Git Checkout
        uses: actions/checkout@v2
      -
        name: Push_Docker Readme
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: yanik39/equivs
